substitutions:
  name: kickstart-bk7231t
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

esphome:
  name: kickstart-bk7231t

libretuya:
  board: generic-bk7231t-qfn32-tuya
  framework:
    version: dev
    
ota:

wifi:
  ssid: $wifi_ssid
  password: $wifi_password
  ap:
    ssid: $name
    password: $wifi_password

captive_portal:

api:

web_server: