esphome:
  name: kickstart-bk7231t

libretuya:
  board: generic-bk7231t-qfn32-tuya
  framework:
    version: dev
    
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: kickstart-bk7231t
    password: !secret wifi_password

captive_portal:

api:

web_server: