esphome:
  name: kickstart-bk7231t

libretuya:
  board: generic-bk7231t-qfn32-tuya
  framework:
    version: dev

logger:
web_server:
captive_portal:
mdns:
api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
