esphome:
  name: kickstart-rtl8710bn-2mb-468k
  project:
    name: lt.web
    version: "1.0"

dashboard_import:
  package_import_url: github://libretuya/esphome-kickstart/yaml/rtl8710bn-2mb-468k.yaml@main
  import_full_config: true

libretuya:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: dev
  loglevel: debug

external_components:
  source: github://libretuya/esphome-kickstart
  components: [pinscan]
  refresh: 10 min

logger:
  baud_rate: 115200
  logs:
    select: ERROR
    sensor: ERROR
    text_sensor: ERROR

ota:

wifi:
  ap:
    ssid: kickstart-rtl8710bn-2mb-468k

captive_portal:

api:
  reboot_timeout: 0s

web_server:
  local: true

pinscan:
  id: scanner
  pin_state_sensor:
    name: -> Pin State

select:
  - platform: template
    id: mode
    name: -> Pin Mode
    options: 
      - INPUT
      - INPUT_PULLUP
      - OUTPUT_HIGH
      - OUTPUT_LOW
    optimistic: true
    on_value:
      - pinscan.set_mode:
          id: scanner
          mode: !lambda "return id(mode).active_index().value();"

  - platform: template
    id: pin
    name: -> Pin
    options: 
      - Select PIN
      - D0 / PA00 / PWM2
      - D1 / PA05 / PWM4
      - D2 / PA06 / FCS
      - D3 / PA07 / FD1
      - D4 / PA08 / FD2
      - D5 / PA09 / FD0
      - D6 / PA10 / FSCK
      - D7 / PA11 / FD3
      - D8 / PA12 / PWM3
      - D9 / PA14 / PWM0 / SWCLK
      - D10 / PA15 / PWM1 / SWDIO
      - D11 / PA18 / UART0_RX / I2C1_SCL / SPI0_SCK / SPI1_SCK
      - D12 / PA19 / UART0_CTS / I2C0_SDA / SPI0_CS / SPI1_CS
      - D13 / PA22 / UART0_RTS / I2C0_SCL / SPI0_MISO / SPI1_MISO / PWM5
      - D14 / PA23 / UART0_TX / I2C1_SDA / SPI0_MISO / SPI1_MISO / PWM0
      - D15 / PA29 / UART2_RX / I2C0_SCL / PWM4
      - D16 / PA30 / UART2_TX / I2C0_SDA / PWM4

    optimistic: true
    on_value:
      - pinscan.set_pin:
          id: scanner
          pin: !lambda "return id(pin).active_index().value() - 1;"
      - pinscan.set_mode:
          id: scanner
          mode: !lambda "return id(mode).active_index().value();"

text_sensor: 
  - platform: wifi_info
    ip_address:
      id: ip_address
      name: IP Address
  - platform: debug
    device:
      name: Device Info
    reset_reason:
      name: Reset Reason
    
button:
  - platform: factory_reset
    name: Reset to Factory Settings

debug:
  update_interval: 5s

sensor:
  - platform: debug
    free:
      name: Heap Free
    loop_time:
      name: Loop Time
    